### ISSUE TITLE
Мысли по поводу 1 этапа

### ISSUE THREAD

**Issue by OITBsuir** [krilop/PFP-PeopleForPeople#11]
Из субъективного:
1) Название таблицы list_of_customer. Правильно понимаю, что тут история посещения мероприятий пользователем? Мб по-другому назвать? (... history или еще как).
2) Название поля geolocation в user_data. Можно перепутать с таблицей geolocation. Это просто адрес человека? Мб просто address назвать?

По остальному:
1) В таблице relation relation_type это внешний ключ, поэтому надо назвать так, как называются внешние ключи по naming convention (в принципе, как поля выше). К тому же он unique. Почему? Это уже в relation_type будет unique.
2) Таблица event_geolocation. Она нужна? Одно событие может быть в нескольких местах? Если да, то тогда остается таблица.
3) Email в таблице authorization. Стоит ли? Предполагаю, что в таблице contact будет тот же самый email. Понимаю, сделано так, чтобы можно было по почте логиниться, но тогда дублирование данных будет (но, если сильно хочется так...)
4) В таблице relation первичным ключом можно сделать связку user_id и friend_id (в принципе, во всех имеющихся таблицах, которые используются для many-to-many, так можно сделать).
5) Таблица user_data -  где первичный ключ?
6) Таблица authorization. Ключ генерируется автоматически? По скрипту не скажешь, что да.
7) По сути поля contact_type в contact и payment_method в event похожи: там выбирается тип чего-то, причем тип ограниченный по количеству (enum , например). Поэтому в payment_method и contact_type можно сделать одинаковым образом или число, или ограниченную по числу символов строку. Потом сюда можно будет через hibernate прописать ordinal или string. Payment_type это же тип оплаты?
8) В таблице geolocation address это точно json?
9) В user_data поле media так и должно быть json? 

Вообще тема интересная для проекта, но будут проблемы))) Как отобразить связь между пользователями в таблице relation? 
Одна запись или две? А как потом искать? Будут костыли)))

**Comment by krilop** [comment]
Что касается вещей субъективных:
1. По задумке, эта таблица будет служить не только историей посещений, но также и будет помогать найти компанию для события. Например, пользователь знает, что хочет пойти на концерт, но не знает с кем. Тогда у него будет возможность посмотреть людей, которые собираются туда пойти. Будет выведено по репутации для пользователя. Первый этап, будет проверяться, не идет ли кто-то из его списка друзей туда. Если никто из его сети контактов не идет, то дальше будут предлагаться люди, которые бы просто попадались ему в предложениях для знакомств(по сути незнакомцы с похожими интересами). А дальше уже пользователю решать, что с этой информацией делать.
2. Согласен, хорошее замечание. Таблица и соответствующие ей поля будут переименованы в address. У пользователя же останется поле geolocation, т.к. оно будет привязано не к конкретному адресу, а к тому, где сейчас находится пользователь.
Что касается остального:
1. Здесь тоже согласен, порядок наведу. По поводу unique, думаю,  это произошло случайно. Исправлю.
2. Действительно, одно событие может быть в нескольких местах. Например, премьера фильма. Очевидно, что показ может быть в разных кинотеатрах. С концертами похожая история. Это же можно спроецировать и на дату события, просто к слову.
3. Попробую защитить своё решение. Для связи администрации с пользователем нужен минимум один его контакт. Проще всего делать рассылки(из-за/для каких-то массовых случаев) поэтому выбрана именно почта. Таблица contact не будет в себе хранить почту. Предполагалось, что эта таблица нужна, если человек хочет дать о себе больше информации, чем позволяет сервис (Это поможет также людям более охотно переходить в приложение, т.к. к данным, которые он добавлял в другие соц. сети, будет доступ по паре нажатий). Например, больше фотографий, аккаунт с музыкой, которую он слушает, но каждый пользователь может захотеть добавить что-то разное,добавить разное количество, а может и не захотеть вовсе. В следствии чего, было решено создать для этого отдельную таблицу.
4. На эту тему я ещё почитаю информацию, позже вернусь к этому вопросу в отдельном комментарии.
5. Authorization и user_data по изначальному замыслу имеют связь one-to-one. Если я правильно понял изучаемые мной источники, первичный ключ там не требуется. Если нет, напишите мне об этом.
6. Уточните, пожалуйста, что вы подразумеваете под ключом. Заранее благодарю.
7. Соглашусь с вашим замечанием. Разные способы были выбраны с целью рассмотреть разные случаи, но если смотреть на ситуацию с описанной вами стороны, то так действительно лучше. Подумаю, что выбрать, и оставлю один вариант. Верно, payment_type - тип оплаты.
8. Json был выбран, т.к. локацию можно указать разными способами. Например, физический адрес, точка на Яндекс карте и точка на Гугл карте. Исходя из моих знаний, json подошел сюда лучше остальных вариантов.
9. В идеале, хранить неограниченное число фотографий. Я почитал про способы хранения изображений, рекомендуют хранить ссылки на них(само изображение хранится где-то в интернете и можно получить доступ к нему по ссылке. Также, это не обязательно будет изображение). 

Я очень рад, что вам понравилась тема моего проекта. Расскажу ниже я расскажу про него чуть больше. Из плюсов, его аналог недавно перестал предоставлять услуги в нашей стране, а потребность осталась. Также, я решил добавить от себя идею, которая пришла мне как-то на досуге. Суть её следующая: очень часто, когда вы собираетесь на свидание, прогулку со своей второй половинкой, или просто погулять с друзьями, вы не знаете, куда можно пойти. Так вот это приложение будет помогать вам выбрать. Оно будет анализировать интересы пользователей( возможно, и посещенные ими ранее мероприятия, но пока об этом не думал. Идея пришла, пока писал ответ) и предлагать им соответствующий досуг. Нравится кино? Пожалуйста, вот вам список премьер, а после определения фильма, где и когда можно прийти, а также вся необходимая информация. Мне показалось, что пользователям было бы важно, какой тип оплаты за посещения мероприятия. Почему я, скорее всего, оставлю везде таблицы типов? Как минимум, способы оплаты. Дело в том, что помимо наличных и безналов, есть заведения, где принимают только определенные виды карт, где нельзя расплачиваться телефоном, а также для пользовательских настроек. Что я имею ввиду? Я хочу дать пользователям возможность самим создавать события. Не знаешь с кем провести новый год? Создай соответствующее событие. И я говорю не только об одном человеке. Пользователь сам может выбрать, сколько человек звать. Не знаешь, с кем можно просто прогуляться по парку и поговорить о жизненных идеалах? Создай соответствующее событие. Хочешь с кем-нибудь вместе что-то приготовить? Создай соответствующее событие! А оплата там может быть совершенно разная. Как "Угостить мороженым", так и "С тебя курица, лук, черный перец, с меня всё остальное".  Похоже, это добавит приложению гибкости. Также это пока только минимальный функционал, да и описать все задумки за раз немного тяжело. Попросту могу что-то забыть.
Прилагаю список потенциальных расширений:
-Добавить чаты
-Если не удалять записи из таблицы list_of_customers, можно будет потом сделать партнерство с какими-то организациями, для продвижения их в списке предлагаемых событий, а они в замен или скидку пользователям, или копеечку в карман компании.
-Добавить совместный досуг прямо в приложении. Например, просмотр фильма, прослушивание музыки.
-Добавить возможность составлять целые маршруты.
-Добавить возможность считать, сколько денег стоит взять с собой в зависимости от маршрута.
-Добавить систему рейтинга на события/заведения. Также можно реализовать систему отзывов.
В общем, тема интересная, привносит новые идеи, а также является очень гибкой. :)
P.s. Изначально не понял о какой проблеме вы говорите касательно таблицы relation. Но примерно на середине объяснения идеи понял, что так будет тяжело искать записи в таблице. Например, нужно вывести всех друзей пользователя. И здесь надо просмотреть два поля на наличие связи. Дальше развивая мысль я понял, в чем проблема. Постараюсь подумать над её решением.

**Comment by OITBsuir** [comment]
По 5 пункту. Ваш внешний ключ будет и первычным одновременно.
По 6 пункту. У Ваших таблиц все первичные ключи generated, как я могу видеть по скрипту, в authorization же нет. Вы сами будет подставлять в коде значения, не полагаясь на базу?
Вы слишком много запланировали, выберите несколько самых интересных для Вас функциональных возможностей, которые вы успеете реализовать в рамках стажировки. Желательно, чтобы они были реализованы на стадии проекта Spring/Hibernate.

**Comment by krilop** [comment]
5. Добавил.
6. Исправил.
Базу сократил.

**Comment by OITBsuir** [comment]
Раз уж таблицы **_contact_** и **_contact_type_**, а также таблицы **_relation_** и **_relation_type_** связываются через внешние ключи, необходимо в коде правильно отметить недостающие внешние ключи и назвать так, как обычно называют внешние ключи "название-таблицы_id". Это единственный момент, можно переходит дальше к следующему этапу.
